---
title: 'HIV-SN in children'
subtitle: 'Descriptive analyses: Demographics and HIV profile'
author: Peter Kamerman 
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: haddock
    code_folding: show
    toc: true
    toc_depth: 4
    toc_float: true
    df_print: paged
---

```{r setup, include = FALSE}
# Load libraries
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(stringr)
library(pander)

# knitr options
knitr::opts_chunk$set(echo = TRUE,
               warning = FALSE, 
               message =  FALSE, 
               dev = 'png',
               fig.align = 'center')

# Import data
data <- read_csv('./data/cleaned_data.csv')

# Trim to demographic and HIV disease data only
data <- select(data, 1:13, Age.years, ART.years)
```

## Quick look at the data
```{r quick_look}
# 'Top-n-tail' data
head(data)
tail(data)

# Check structure
glimpse(data)
```

## Demographic data
### Sex
```{r sex}
# Summarise data
sex <- summary(factor(data$Sex))
sex <- c(sex, 
         round(nrow(data[data$Sex == 'Female', ]) / nrow(data) * 100))
sex <- data_frame(Female = sex[[1]],
                  Male = sex[[2]],
                  '% Female' = sex[[3]])

# Print summary
pander(sex, caption = 'Number of males and females')
```

### Age
```{r age}
## Summarise data
age <- data %>%
    select(Age.years) %>%
    summarise(`Age (years)` = round(mean(Age.years), 1),
              SD = round(sd(Age.years), 1))

## Print summary
pander(age, caption = 'Mean age of the children')

## Plot data
qplot(data$Age.years, 
      geom = c('boxplot', 'jitter'), 
      x = 'Children\n(n = 135)', 
      ylab = 'Years', 
      main = 'Age') +
    theme_minimal(base_size = 16) +
    theme(axis.title.x = element_blank())
```

### Weight for age 
```{r weight}
## Summarise data
waz <- summary(data$WAZ)

## Print summary table
pander(waz, caption = 'Weight for age (z-score)')

## Plot data
qplot(data$WAZ, 
      geom = c('boxplot', 'jitter'), 
      ylim = c(-2, 2), 
      x = 'Children\n(n = 135)', 
      ylab = 'z-score', 
      main = 'Weight for age') +
    geom_hline(yintercept = 0, colour = 'red') +
    theme_minimal(base_size = 16) +
    theme(axis.title.x = element_blank())
```

### Height for age 
```{r HAZ}
## Summarise data
haz <- summary(data$HAZ)

## Print summary table
pander(haz, caption = 'Height for age (z-score)')

## Plot data 
qplot(data$HAZ, 
      geom = c('boxplot', 'jitter'), 
      ylim = c(-2, 2), 
      x = 'Children\n(n = 135)', 
      ylab = 'z-score', 
      main = 'Height for age') +
    geom_hline(yintercept = 0, colour = 'red') +
    theme_minimal(base_size = 16) +
    theme(axis.title.x = element_blank())
```

## Disease data
### Most recent CD4
```{r cd4}
# Summarise data
cd4 <- summary(data$CD4)

## Print summary table
pander(cd4, caption = 'Most recent CD4 T-cell count (cells/mm3)')

## Plot data
qplot(data$CD4, 
      geom = c('boxplot', 'jitter'), 
      x = 'Children\n(n = 135)', 
      ylab = 'CD4 T-cell count (cells/mm3)', 
      main = 'Most recent CD4 T-cell count') +
    theme_minimal(base_size = 16) +
    theme(axis.title.x = element_blank())
```

### Most recent viral load
```{r viral_load}
## Summarise data
vl <- summary(log10(data$Viral.load))

## Print summary table
pander(vl, caption = 'Most recent viral load [log10(copies/ml)]')

## Plot data
qplot(log10(data$Viral.load), 
      geom = c('boxplot', 'jitter'), 
      x = 'Children\n(n = 135)', 
      ylab = 'Viral load [log10(copies/ml)]', 
      main = 'Most recent viral load') +
    theme_minimal(base_size = 16) +
    theme(axis.title.x = element_blank())
```

## Treatment data
### Current ART regimen
```{r art}
## Get names for ordering factor
foo_names <- data %>%
    select(ART.regimen) %>%
    filter(!is.na(ART.regimen)) %>%
    group_by(ART.regimen) %>%
    summarise(foo_names = unique(ART.regimen)) %>%
    select(foo_names) %>%
    .$foo_names

## Get counts and arrange with NA last
foo <- data %>%
    mutate(ART.regimen = str_replace_na(ART.regimen)) %>%
    group_by(ART.regimen) %>%
    summarise(n = n()) %>%
    mutate(ART.regimen = factor(ART.regimen,
                                levels = c(foo_names, 'NA'),
                                ordered = TRUE)) %>%
    # Add percents
    ungroup() %>%
    mutate('%' = round(n / sum(n) * 100)) %>%
    arrange(desc(n))

## Print table
pander(foo, 
       caption = 'Current ART regimen',
       justify = 'lrr',
       split.tables = Inf)
```

### D4T ever
```{r d4t_ever}
## Get counts and arrange with NA last
bar <- data %>%
    mutate(d4T.ever = str_replace_na(d4T.ever)) %>%
    group_by(d4T.ever) %>%
    summarise(n = n()) %>%
    mutate(d4T.ever = factor(d4T.ever,
                             levels = c('Yes', 'No', 'NA'),
                             ordered = TRUE)) %>%
    # Add percents
    ungroup() %>%
    mutate('%' = round(n / sum(n) * 100)) %>%
    arrange(d4T.ever)

## Print table
pander(bar, 
       caption = 'd4T use: ever',
       justify = 'lrr',
       split.tables = Inf)
```

### Currently on d4T
```{r d4t_now}
## Process data
baz <- data %>%
    select(ART.regimen, d4T.ever) %>%
    mutate(ART.regimen = str_replace_na(ART.regimen),
           d4T.ever = str_replace_na(d4T.ever)) %>%
    mutate(d4T.now = ifelse(str_detect(ART.regimen, 
                                       pattern = 'D4T') == TRUE,
                            'Yes', ifelse(str_detect(ART.regimen, 
                                                     pattern = 'NA') == TRUE,
                                          'NA', 'No'))) 

## Get counts and arrange with NA last
baz2 <- baz %>%
    group_by(d4T.now) %>%
    summarise(n = n()) %>%
    mutate(d4T.now = factor(d4T.now,
                            levels = c('Yes', 'No', 'NA'),
                            ordered = TRUE)) %>%
    arrange(d4T.now) %>%
    # Add percents
    ungroup() %>%
    mutate('%' = round(n / sum(n) * 100)) %>%
    arrange(d4T.now)

## Print table
pander(baz2, 
       caption = 'd4T use: current',
       justify = 'lrr',
       split.tables = Inf)
```

### Previous D4T use
```{r d4t_previous}
## Get counts and arrange with NA last
cux <- baz %>%
    mutate(d4T.previous = ifelse(c(d4T.ever == 'Yes' & d4T.now == 'No'),
                            'Yes', ifelse(d4T.now == 'No',
                                          'No', 'NA'))) %>%
    group_by(d4T.previous) %>%
    summarise(n = n()) %>%
    mutate(d4T.previous = factor(d4T.previous, 
                                 levels = c('Yes', 'No', 'NA'),
                                 ordered = TRUE)) %>%
    arrange(d4T.previous) %>%
    # Add percents
    ungroup() %>%
    mutate('%' = round(n / sum(n) * 100)) %>%
    arrange(d4T.previous)

## Print table
pander(cux, 
       caption = 'd4T use: previous', 
       justify = 'lrr',
       split.tables = Inf)
```

## Session infomation
```{r session_info, echo = F, warning = F, message = F}
pander(sessionInfo())
```
