---
title: 'HIV-SN in children'
subtitle: 'Descriptive analyses: Motor development'
author: Peter Kamerman 
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: haddock
    code_folding: show
    toc: true
    toc_depth: 4
    toc_float: true
    df_print: paged
---

```{r setup, include = FALSE}
# Load libraries
library(purrr)
library(dplyr)
library(tidyr)
library(tibble)
library(stringr)
library(readr)
library(forcats)
library(ggplot2)
library(scales)
library(pander)
library(boot)

# knitr options
knitr::opts_chunk$set(echo = TRUE,
               warning = FALSE, 
               message =  FALSE)

# Import data
data <- read_csv('./data/cleaned_data.csv')

# Trim df to required variables
data <- data %>%
    select(ID, 
           starts_with('MABC'),
           -ends_with('.score'))

# Palette
pal <- RColorBrewer::brewer.pal(9, 'YlOrBr')[3:9]

# Generate new columns placing percentiles into categories
data <- data %>%
    mutate(manual.dex.5th = ifelse(MABC.manual.dex.percentile <= 5,
                                   yes = 'yes', no = 'no'),
           manual.dex.10th = ifelse(MABC.manual.dex.percentile <= 10,
                                   yes = 'yes', no = 'no'),
           manual.dex.25th = ifelse(MABC.manual.dex.percentile <= 25,
                                   yes = 'yes', no = 'no'),
           manual.dex.50th = ifelse(MABC.manual.dex.percentile <= 50,
                                   yes = 'yes', no = 'no'),
           manual.dex.75th = ifelse(MABC.manual.dex.percentile <= 75,
                                   yes = 'yes', no = 'no'),
           manual.dex.95th = ifelse(MABC.manual.dex.percentile <= 95,
                                   yes = 'yes', no = 'no'),
           manual.dex.99th = ifelse(MABC.manual.dex.percentile <= 99,
                                   yes = 'yes', no = 'no')) %>%
    mutate(throw.5th = ifelse(MABC.throw.percentile <= 5,
                                   yes = 'yes', no = 'no'),
           throw.10th = ifelse(MABC.throw.percentile <= 10,
                                   yes = 'yes', no = 'no'),
           throw.25th = ifelse(MABC.throw.percentile <= 25,
                                   yes = 'yes', no = 'no'),
           throw.50th = ifelse(MABC.throw.percentile <= 50,
                                   yes = 'yes', no = 'no'),
           throw.75th = ifelse(MABC.throw.percentile <= 75,
                                   yes = 'yes', no = 'no'),
           throw.95th = ifelse(MABC.throw.percentile <= 95,
                                   yes = 'yes', no = 'no'),
           throw.99th = ifelse(MABC.throw.percentile <= 99,
                                   yes = 'yes', no = 'no')) %>%
    mutate(balance.5th = ifelse(MABC.balance.percentile <= 5,
                                   yes = 'yes', no = 'no'),
           balance.10th = ifelse(MABC.balance.percentile <= 10,
                                   yes = 'yes', no = 'no'),
           balance.25th = ifelse(MABC.balance.percentile <= 25,
                                   yes = 'yes', no = 'no'),
           balance.50th = ifelse(MABC.balance.percentile <= 50,
                                   yes = 'yes', no = 'no'),
           balance.75th = ifelse(MABC.balance.percentile <= 75,
                                   yes = 'yes', no = 'no'),
           balance.95th = ifelse(MABC.balance.percentile <= 95,
                                   yes = 'yes', no = 'no'),
           balance.99th = ifelse(MABC.balance.percentile <= 99,
                                   yes = 'yes', no = 'no')) %>%
    mutate(total.5th = ifelse(MABC.total.percentile <= 5,
                                   yes = 'yes', no = 'no'),
           total.10th = ifelse(MABC.total.percentile <= 10,
                                   yes = 'yes', no = 'no'),
           total.25th = ifelse(MABC.total.percentile <= 25,
                                   yes = 'yes', no = 'no'),
           total.50th = ifelse(MABC.total.percentile <= 50,
                                   yes = 'yes', no = 'no'),
           total.75th = ifelse(MABC.total.percentile <= 75,
                                   yes = 'yes', no = 'no'),
           total.95th = ifelse(MABC.total.percentile <= 95,
                                   yes = 'yes', no = 'no'),
           total.99th = ifelse(MABC.total.percentile <= 99,
                                   yes = 'yes', no = 'no'))
    
```

## Quick look

**Data are reported as age-adjusted percentile scores**

```{r quick_look}
# 'Top-n-tail' data
head(data)
tail(data)

# Check structure
glimpse(data)
```

## Performance domains

### Boot function
```{r boot_functions}
############################################################
#                                                          #
#                      Boot functions                      #
#                                                          #
############################################################
# Use package 'boot' to bootstrap 95%CI of percent children in specified percentiles
mabc <- function(data, i) {
    dat <- data[i]
    dat_percent <- round(sum(dat == 'yes', rm.na = TRUE) / length(dat) * 100, 1)
    return(dat_percent)
}
```

### Dexterity
```{r dexterity}
# Complete cases
data_dex <- data[!is.na(data$MABC.manual.dex.percentile), ]
nrow(data_dex)

# Exploratory plot
qplot(data = data, y = MABC.manual.dex.percentile, x = '', 
      geom = c('boxplot', 'jitter'), ylim = c(0, 100),
      main = 'MABC manual dexterity', 
      ylab = 'Performance (percentile)\n') +
    scale_y_continuous(breaks = c(5, 10, 25, 50, 75, 95),
                       labels = c(5, 10, 25, 50, 75, 95)) +
    # Add percentiles
    geom_hline(yintercept = 5, colour = pal[[2]]) +
    geom_hline(yintercept = 10, colour = pal[[3]]) +
    geom_hline(yintercept = 25, colour = pal[[4]]) +
    geom_hline(yintercept = 50, colour = pal[[5]]) +
    geom_hline(yintercept = 75, colour = pal[[6]]) +
    geom_hline(yintercept = 95, colour = pal[[7]]) +
    theme_minimal(base_size = 14) +
    theme(panel.grid = element_blank(),
          axis.title.x = element_blank())

# Summary table
dex_tab <- data %>%
    select(ID, 
           starts_with('manual.dex')) %>%
    gather(key = Percentile,
           value = Present,
           -ID) %>%
    separate(col = Percentile, 
             into = c('extra', 'extra2', 'Percentile'),
             sep = '\\.') %>%
    select(-starts_with('extra')) %>%
    group_by(Percentile, Present) %>%
    summarise(`Cumulative count` = n(),
              `Cumulative percent` = round(sum(Present == 'yes') / nrow(data) * 100, 1)) %>%
    ungroup() %>%
    filter(Present == 'yes') %>%
    select(Percentile, `Cumulative count`, `Cumulative percent`) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile))

# Bootstrap
dex_boot <- data %>%
    select(starts_with('manual.dex')) %>%
    # Apply bootstrap function
    map(~boot(., statistic = mabc, R = 1000)) %>%
    # Generate CI
    map(~boot.ci(., type = 'basic')) %>%
    # Remove NULL elements
    .[sapply(., Negate(is.null))] %>%
    as_data_frame() %>%
    # Extract CI
    dmap(~paste(round(.$basic[4], 1), ' to ', round(.$basic[5], 1))) %>%
    # Get ready for join
    gather(key = Percentile,
           value = '95% CI') %>%
    separate(col = Percentile, 
             into = c('extra', 'extra2', 'Percentile'),
             sep = '\\.') %>%
    select(-starts_with('extra')) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile)) %>%
    # Fix maths > 100% issue
    mutate(`95% CI` = str_replace(`95% CI`,
                                  pattern = '10*.*$',
                                  replacement = '100.0'))

# Join
dex_tab <- dex_tab %>%
    left_join(dex_boot, by = 'Percentile')

# Table
pander(dex_tab, 
       caption = 'MABC manual dexterity performance', 
       justify = 'lrrr')
```

### Balance
```{r balance}
# Complete cases
data_balance <- data[!is.na(data$MABC.balance.percentile), ]
nrow(data_balance)

# Exploratory plot
qplot(data = data, y = MABC.balance.percentile, x = '', 
      geom = c('boxplot', 'jitter'), ylim = c(0, 100),
      main = 'MABC balance', 
      ylab = 'Performance (percentile)\n') +
    scale_y_continuous(breaks = c(5, 10, 25, 50, 75, 95),
                       labels = c(5, 10, 25, 50, 75, 95)) +
    # Add percentiles
    geom_hline(yintercept = 5, colour = pal[[2]]) +
    geom_hline(yintercept = 10, colour = pal[[3]]) +
    geom_hline(yintercept = 25, colour = pal[[4]]) +
    geom_hline(yintercept = 50, colour = pal[[5]]) +
    geom_hline(yintercept = 75, colour = pal[[6]]) +
    geom_hline(yintercept = 95, colour = pal[[7]]) +
    theme_minimal(base_size = 14) +
    theme(panel.grid = element_blank(),
          axis.title.x = element_blank())

# Summary table
balance_tab <- data %>%
    select(ID, 
           starts_with('balance')) %>%
    gather(key = Percentile,
           value = Present,
           -ID) %>%
    separate(col = Percentile, 
             into = c('extra', 'Percentile'),
             sep = '\\.') %>%
    select(-extra) %>%
    group_by(Percentile, Present) %>%
    summarise(`Cumulative count` = n(),
              `Cumulative percent` = round(sum(Present == 'yes') / nrow(data) * 100, 1)) %>%
    ungroup() %>%
    filter(Present == 'yes') %>%
    select(Percentile, `Cumulative count`, `Cumulative percent`) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile))

# Bootstrap
balance_boot <- data %>%
    select(starts_with('balance')) %>%
    # Apply bootstrap function
    map(~boot(., statistic = mabc, R = 1000)) %>%
    # Generate CI
    map(~boot.ci(., type = 'basic')) %>%
    # Remove NULL elements
    .[sapply(., Negate(is.null))] %>%
    as_data_frame() %>%
    # Extract CI
    dmap(~paste(round(.$basic[4], 1), ' to ', round(.$basic[5], 1))) %>%
    # Get ready for join
    gather(key = Percentile,
           value = '95% CI') %>%
    separate(col = Percentile, 
             into = c('extra', 'Percentile'),
             sep = '\\.') %>%
    select(-extra) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile)) %>%
    # Fix maths > 100% issue
    mutate(`95% CI` = str_replace(`95% CI`,
                                  pattern = '10[0-9]\\.[0-9]',
                                  replacement = '100.0'))

# Join
balance_tab <- balance_tab %>%
    left_join(balance_boot, by = 'Percentile')

pander(balance_tab, 
       caption = 'MABC Balance performance', 
       justify = 'lrrr')
```

### Throwing
```{r throwing}
# Complete cases
data_throw <- data[!is.na(data$MABC.throw.percentile), ]
nrow(data_throw)

# Exploratory plot
qplot(data = data, y = MABC.throw.percentile, x = '', 
      geom = c('boxplot', 'jitter'), ylim = c(0, 100),
      main = 'MABC throwing', 
      ylab = 'Performance (percentile)\n') +
    scale_y_continuous(breaks = c(5, 10, 25, 50, 75, 95),
                       labels = c(5, 10, 25, 50, 75, 95)) +
    # Add percentiles
    geom_hline(yintercept = 5, colour = pal[[2]]) +
    geom_hline(yintercept = 10, colour = pal[[3]]) +
    geom_hline(yintercept = 25, colour = pal[[4]]) +
    geom_hline(yintercept = 50, colour = pal[[5]]) +
    geom_hline(yintercept = 75, colour = pal[[6]]) +
    geom_hline(yintercept = 95, colour = pal[[7]]) +
    theme_minimal(base_size = 14) +
    theme(panel.grid = element_blank(),
          axis.title.x = element_blank())

# Summary table
throw_tab <- data %>%
    select(ID, 
           starts_with('throw')) %>%
    gather(key = Percentile,
           value = Present,
           -ID) %>%
    separate(col = Percentile, 
             into = c('extra', 'Percentile'),
             sep = '\\.') %>%
    select(-extra) %>%
    group_by(Percentile, Present) %>%
    summarise(`Cumulative count` = n(),
              `Cumulative percent` = round(sum(Present == 'yes') / nrow(data) * 100, 1)) %>%
    ungroup() %>%
    filter(Present == 'yes') %>%
    select(Percentile, `Cumulative count`, `Cumulative percent`) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile))

# Bootstrap
throw_boot <- data %>%
    select(starts_with('throw')) %>%
    # Apply bootstrap function
    map(~boot(., statistic = mabc, R = 1000)) %>%
    # Generate CI
    map(~boot.ci(., type = 'basic')) %>%
    # Remove NULL elements
    .[sapply(., Negate(is.null))] %>%
    as_data_frame() %>%
    # Extract CI
    dmap(~paste(round(.$basic[4], 1), ' to ', round(.$basic[5], 1))) %>%
    # Get ready for join
    gather(key = Percentile,
           value = '95% CI') %>%
    separate(col = Percentile, 
             into = c('extra', 'Percentile'),
             sep = '\\.') %>%
    select(-extra) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile)) %>%
    # Fix maths > 100% issue
    mutate(`95% CI` = str_replace(`95% CI`,
                                  pattern = '10[0-9]\\.[0-9]',
                                  replacement = '100.0'))

# Join
throw_tab <- throw_tab %>%
    left_join(throw_boot, by = 'Percentile')


pander(throw_tab, 
       caption = 'MABC throwing performance', 
       justify = 'lrrr')
```

### Overall
```{r overall}
# Complete cases
data_total <- data[!is.na(data$MABC.total.percentile), ]
nrow(data_total)

# Exploratory plot
qplot(data = data, y = MABC.total.percentile, x = '', 
      geom = c('boxplot', 'jitter'), ylim = c(0, 100),
      main = 'MABC total', 
      ylab = 'Performance (percentile)\n') +
    scale_y_continuous(breaks = c(5, 10, 25, 50, 75, 95),
                       labels = c(5, 10, 25, 50, 75, 95)) +
    # Add percentiles
    geom_hline(yintercept = 5, colour = pal[[2]]) +
    geom_hline(yintercept = 10, colour = pal[[3]]) +
    geom_hline(yintercept = 25, colour = pal[[4]]) +
    geom_hline(yintercept = 50, colour = pal[[5]]) +
    geom_hline(yintercept = 75, colour = pal[[6]]) +
    geom_hline(yintercept = 95, colour = pal[[7]]) +
    theme_minimal(base_size = 14) +
    theme(panel.grid = element_blank(),
          axis.title.x = element_blank())

# Summary table
total_tab <- data %>%
    select(ID, 
           starts_with('total')) %>%
    gather(key = Percentile,
           value = Present,
           -ID) %>%
    separate(col = Percentile, 
             into = c('extra', 'Percentile'),
             sep = '\\.') %>%
    select(-extra) %>%
    group_by(Percentile, Present) %>%
    summarise(`Cumulative count` = n(),
              `Cumulative percent` = round(sum(Present == 'yes') / nrow(data) * 100, 1)) %>%
    ungroup() %>%
    filter(Present == 'yes') %>%
    select(Percentile, `Cumulative count`, `Cumulative percent`) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile))

# Bootstrap
total_boot <- data %>%
    select(starts_with('total')) %>%
    # Apply bootstrap function
    map(~boot(., statistic = mabc, R = 1000)) %>%
    # Generate CI
    map(~boot.ci(., type = 'basic')) %>%
    # Remove NULL elements
    .[sapply(., Negate(is.null))] %>%
    as_data_frame() %>%
    # Extract CI
    dmap(~paste(round(.$basic[4], 1), ' to ', round(.$basic[5], 1))) %>%
    # Get ready for join
    gather(key = Percentile,
           value = '95% CI') %>%
    separate(col = Percentile, 
             into = c('extra', 'Percentile'),
             sep = '\\.') %>%
    select(-extra) %>%
    mutate(Percentile = 
               fct_relevel(Percentile,
                           '5th', '10th', '25th', '50th', '75th', '95th', '99th')) %>%
    arrange(Percentile) %>%
    mutate(Percentile = as.character(Percentile)) %>%
    # Fix maths > 100% issue
    mutate(`95% CI` = str_replace(`95% CI`,
                                  pattern = '10[0-9]\\.[0-9]',
                                  replacement = '100.0'))

# Join
total_tab <- total_tab %>%
    left_join(total_boot, by = 'Percentile')


pander(total_tab, 
       caption = 'MABC total performance', 
       justify = 'lrrr')
```

### Traffic light
```{r traffic_light}
traffic_plot <- data %>%
    select(MABC.zone) %>%
    group_by(MABC.zone) %>%
    summarise(n = n(),
              percent = round(100 * (n / nrow(.)), 1)) %>%
    arrange(desc(n)) %>%
    mutate(Zone = fct_inorder(c('Green', 'Amber', 'Red'))) %>%
    select(Zone, n, percent) %>%
    add_column(x_value = c(5, 5, 5)) %>%
    add_column(x_value_text = c(1, 1, 1)) %>%
    add_column(y_values = c(2, 1.45, 1)) %>%
    add_column(text = sprintf('%s Zone (N: %d; Percent: %.0f%%):', 
                           .$Zone, .$n, .$percent)) 

ggplot(data = traffic_plot) +
    aes(x = x_value, y = y_values, fill = Zone, size = percent) +
    geom_rect(xmin = 3.8, xmax = 6.2, ymin = 0.9, ymax = 2.25, fill = '#323232') +
    geom_point(shape = 21) +
    geom_text(aes(x = x_value_text, label = text), size = 5, hjust = 'left') +
    scale_y_continuous(limits = c(0.9, 2.25), expand = c(0,0)) +
    scale_x_continuous(limits = c(0.8, 6.2), expand = c(0,0)) +
    scale_size_continuous(range = c(30, 80)) +
    scale_fill_manual(values = c('#2dc937', '#e7b416', '#cc3232')) +
    theme_minimal(base_size = 14) +
    theme(legend.position = 'none',
          axis.title = element_blank(),
          axis.text = element_blank(),
          panel.grid = element_blank())
```

## Session infomation
```{r session_info, echo = F, warning = F, message = F}
pander(sessionInfo())
```

