---
title: 'HIV-SN in children'
subtitle: 'Data analysis: Risk factors for SN'
author: Natalie Benjamin, Joanne Potterton, and Peter Kamerman 
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: haddock
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include = FALSE}
# Load libraries
library(tidyverse)
library(coin)
library(pander)

# knitr options
knitr::opts_chunk$set(echo = TRUE,
               warning = FALSE, 
               message =  FALSE, 
               cache = TRUE,
               fig.path = './figures/sn-risk/',
               tidy = FALSE)
```


```{r data_import}
# Import data
data <- read_csv('./data/cleaned_data.csv')

# Trim df to required variables
data <- data %>%
    select(ID,
           Neuropathy,
           Age.years,
           Sex,
           WAZ,
           HAZ,
           CD4,
           Viral.load,
           d4T.ever,
           ART.years)
```

## Quick look
```{r quick_look}
# 'Top-n-tail' data
head(data)
tail(data)

# Check structure
glimpse(data)
```

## Predictors
**NOTE:** 

- _Predictors for symptomatic SN not explored because of the very small sample size._

** Examined:** 

- _Age, sex, height for age, weight for age, CD4 T-cell count, and viral load_

```{r sn_predictors}
############################################################
#                                                          #
#                           Age                            #
#                                                          #
############################################################
# Select data and filter out incomplete cases
age <- data %>%
    select(Age.years, Neuropathy) %>%
    filter(complete.cases(.))
# Plot
qplot(data = age, x = Neuropathy, y = Age.years, 
      geom = c('boxplot', 'jitter'))
# Stats
wilcox_test(Age.years ~ factor(Neuropathy), 
            data = age,
            distribution = 'exact',
            conf.int = TRUE)

############################################################
#                                                          #
#                           Sex                            #
#                                                          #
############################################################
# Select data and filter out incomplete cases
sex <- data %>%
    select(Sex, Neuropathy) %>%
    filter(complete.cases(.)) %>%
    table()
# Plot
mosaicplot(sex)
# Stats
chisq_test(sex,
           distribution = 'exact')

############################################################
#                                                          #
#                      Height for age                      #
#                                                          #
############################################################
# Select data and filter out incomplete cases
haz <- data %>%
    select(HAZ, Neuropathy) %>%
    filter(complete.cases(.))
# Plot
qplot(data = haz, x = Neuropathy, y = HAZ, 
      geom = c('boxplot', 'jitter'))
## Stats
wilcox_test(HAZ ~ factor(Neuropathy),
            data = haz,
            distribution = 'exact',
            conf.int = TRUE)

############################################################
#                                                          #
#                      Weight for age                      #
#                                                          #
############################################################
# Select data and filter out incomplete cases
waz <- data %>%
    select(WAZ, Neuropathy) %>%
    filter(complete.cases(.))
# Plot
qplot(data = waz, x = Neuropathy, y = WAZ, 
      geom = c('boxplot', 'jitter'))
# Stats
wilcox_test(WAZ ~ factor(Neuropathy),
            data = waz,
            distribution = 'exact',
            conf.int = TRUE)

############################################################
#                                                          #
#                           CD4                            #
#                                                          #
############################################################
# Select data and filter out incomplete cases
cd4 <- data %>%
    select(CD4, Neuropathy) %>%
    filter(complete.cases(.))
# Plot
qplot(data = cd4, x = Neuropathy, y = CD4, 
      geom = c('boxplot', 'jitter'))
## Stats
wilcox_test(CD4 ~ factor(Neuropathy),
            data = cd4,
            distribution = 'exact',
            conf.int = TRUE)

############################################################
#                                                          #
#                   (Log10)Viral load                      #
#                                                          #
############################################################
# Select data and filter out incomplete cases
vl <- data %>%
    select(Viral.load, Neuropathy) %>%
    filter(complete.cases(.)) %>%
    mutate(log10_viral.load = log10(Viral.load))
# Plot
qplot(data = vl, x = Neuropathy, y = log10_viral.load, 
      geom = c('boxplot', 'jitter'))
# Stats
wilcox_test(log10_viral.load ~ factor(Neuropathy), 
            data = vl, 
            distribution = 'exact',
            conf.int = TRUE)

############################################################
#                                                          #
#                         D4T ever                         #
#                                                          #
############################################################
# Select data and filter out incomplete cases
d4t <- data %>%
    select(d4T.ever, Neuropathy) %>%
    filter(complete.cases(.)) %>%
    table()
# Plot
mosaicplot(d4t)
# Stats
chisq_test(d4t,
           distribution = 'exact',
           conf.int = TRUE)

############################################################
#                                                          #
#                       ART duration                       #
#                                                          #
############################################################
# Select data and filter out incomplete cases
art.duration <- data %>%
    select(ART.years, Neuropathy) %>%
    filter(complete.cases(.))
# Plot
qplot(data = art.duration, x = Neuropathy, y = ART.years,
      geom = c('boxplot', 'jitter'))
# Stats
wilcox_test(ART.years ~ factor(Neuropathy),
            data = art.duration,
            distribution = 'exact',
            conf.int = TRUE)
```

## Session infomation
```{r session_info, echo = F, warning = F, message = F}
pander(sessionInfo())
```

