---
title: 'HIV-SN in children'
subtitle: 'Descriptive analyses: Quality of life'
author: Peter Kamerman 
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: haddock
    code_folding: show
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r setup, include = FALSE}
# Load libraries
library(tidyverse)
library(stringr)
library(knitr)
library(pander)
library(boot)

# knitr options
knitr::opts_chunk$set(echo = TRUE,
               warning = FALSE, 
               message =  FALSE, 
               fig.align = 'center')
```


```{r data_import}
# Import data
data <- read_csv('./data/cleaned_data.csv')

# Trim df to prevalence data
data <- select(data,
               ID,
               Neuropathy,
               Neuropathy_pin,
               starts_with('PEDQL'),
               starts_with('MABC'))
```

### Quick look
```{r quick_look}
# 'Top-n-tail' data
head(data)
tail(data)

# Check structure
glimpse(data)
```

## QoL summaries
```{r qol_sumaries}
qol.physical <- data %>% 
    select(ID, contains('physical')) %>%
    gather(key = PEDQL.physical, value = Value.physical, 
           PEDQL.parent.physical, PEDQL.child.physical) %>%
    arrange(ID) %>%
    mutate(Sort = seq(1:nrow(.)))

qol.psychosocial <- data %>% 
    select(ID, contains('psychosocial')) %>%
    gather(key = PEDQL.psychosocial, value = Value.psychosocial, 
           PEDQL.parent.psychosocial, PEDQL.child.psychosocial) %>%
    arrange(ID) %>%
    mutate(Sort = seq(1:nrow(.)))

qol.total <- data %>% 
    select(ID, contains('total')) %>%
    gather(key = PEDQL.total, value = Value.total, 
           PEDQL.parent.total, PEDQL.child.total) %>%
    arrange(ID) %>%
    mutate(Sort = seq(1:nrow(.)))

qol <- qol.physical %>%
    left_join(qol.psychosocial, by = 'Sort') %>%
    left_join(qol.total, by = 'Sort') %>%
    select(-ID.x, -ID.y, -Sort)
```

### Prevalence summaries
#### SN prevalence (whole cohort) 
```{r sn_prevalence}
# Counts
sn_point <- data %>%  
    group_by(Neuropathy) %>%  
    summarise(N = n(), Percent = 100 * (n() / nrow(data)))
pander(sn_point[ , 1:2], 
       caption = 'SN vs SN-free (count)', justify = 'lr')
# Bootstrap 95% CI
sn_boot <- boot(data = data, 
              statistic = sn_prev, 
              R = 10000)
sn_bootCI <- boot.ci(sn_boot, type = 'basic')
# Summary table
sn_tab <- data_frame(Group = 'Neuropathy',
                     `Point prevalence` = round(sn_point$Percent[2], 1),
                     `Lower 95% CI limit` = round(sn_bootCI$basic[4], 1),
                     `Upper 95% CI limit` = round(sn_bootCI$basic[5], 1)) 
pander(sn_tab[ , 2:4], 
       caption = 'Prevalence of SN (%)', justify = 'rrr')
# Plot
ggplot(sn_tab) +
    aes(x = Group, y = `Point prevalence`) +
    geom_errorbar(aes(ymin = `Lower 95% CI limit`,
                      ymax = `Upper 95% CI limit`),
                  width = 0.2, size = 1) +
    coord_cartesian(ylim = c(0, 100)) +
    geom_point(size = 10) +
    labs(title = 'Prevalence (95% CI) of HIV-SN\nin 135 HIV+ children',
         y = 'Prevalence (%)\n',
         x = 'HIV-SN') +
    theme(legend.position = 'none',
          axis.text.x = element_blank())
```

#### Symptomatic SN+ (SN+ cohort only)
```{r symp_sn_prevalence}
# Subset out the SN+ participants
data.sn_only <- data %>%
    filter(Neuropathy == 'Yes')
# Counts
symp.sn_point <- data.sn_only %>%  
    group_by(Symp.Neuropathy) %>%  
    summarise(N = n(), Percent = 100 * (n() / nrow(data.sn_only)))
pander(symp.sn_point[ , 1:2], 
       caption = 'Symptomatic SN (SN+ only, count)', justify = 'lr')
# Bootstrap 95% CI
symp.sn_boot <- boot(data = data.sn_only, 
                     statistic = symp.sn_prev, 
                     R = 10000)
symp.sn_bootCI <- boot.ci(symp.sn_boot, type = 'basic')
# Summary table
symp.sn_tab <- data_frame(Group = 'Symptomatic HIV-SN',
                          `Point prevalence` = round(symp.sn_point$Percent[2], 1),
                          `Lower 95% CI limit` = round(symp.sn_bootCI$basic[4], 1),
                          `Upper 95% CI limit` = round(symp.sn_bootCI$basic[5], 1))
pander(symp.sn_tab[ , 2:4], 
       caption = 'Prevalence of Symptomatic SN (SN+ only, %)', justify = 'rrr')
# Plot
ggplot(symp.sn_tab) +
    aes(x = Group, y = `Point prevalence`) +
    geom_errorbar(aes(ymin = `Lower 95% CI limit`,
                      ymax = `Upper 95% CI limit`),
                  width = 0.2, size = 1) +
    coord_cartesian(ylim = c(0, 100)) +
    geom_point(size = 10) +
    labs(title = 'Prevalence (95% CI) of symptomatic HIV-SN\nin 18 HIV+ children with SN',
         y = 'Prevalence (%)\n',
         x = 'Symptomatic HIV-SN\n(SN+ only)') +
    theme(legend.position = 'none',
          axis.text.x = element_blank())
```

## Characteristics of symptomatic SN
```{r symptoms}
############################################################
#                                                          #
#     Not very informative because of the small number     #
#         (n = 5) of children with symptomatic SN          #
#                                                          #
############################################################
# Filter out only those with symptomatic SN (primary definition)
symptomatic_sn <- data %>%
    filter(Symp.Neuropathy == 'Yes')
# Extract symptoms
symptoms_sn <- symptomatic_sn %>%
    select(BPNS.numbness, BPNS.prev.pain, BPNS.current.pain, BPNS.pin.n.needles,
           Other.symp.itching, Other.symp.cramping, Other.symp.painful.cold)
# Table point estimates of symptom prevalences (%)
symptom_tab <- symptoms_sn %>%
    map_df(~ round(sum(.x == 'Yes', na.rm = TRUE) / length(.x) * 100, 1)) %>%
    as.matrix() %>%
    as.table()
# Reorder
symptom_tab2 <- symptom_tab[, order(-symptom_tab)]
# Convert back to df
symptom_tab3 <- symptom_tab2 %>%
    t() %>%
    data.frame() %>%
    tbl_df() %>%
    rename(Numbness = BPNS.numbness, 
           `Previous pain` = BPNS.prev.pain,
           `Current pain` = BPNS.current.pain, 
           `Pins and needles` =BPNS.pin.n.needles,
           Itch = Other.symp.itching, 
           Cramping = Other.symp.cramping, 
           `Painful cold` = Other.symp.painful.cold)
pander(symptom_tab3, 
       caption = 'Prevalence (%) of symptoms in 5 children with symptomatic HIV-SN', 
       justify = 'rrrrrrr', split.tables = Inf)
```

## Characteristics of SN signs
```{r signs}
# Filter out only those with SN
sn_signs <- data %>%
    filter(Neuropathy == 'Yes')
# Extract signs
signs_sn <- sn_signs %>%
    select(BPNS.absent.reflex.RL, BPNS.reduced.vibration.RL)
# Table point estimates of signs prevalences (%)
signs_tab <- signs_sn %>%
    map_df(~ round(sum(.x == 'Yes', na.rm = TRUE) / length(.x) * 100, 1)) %>%
    as.matrix() %>%
    as.table()
# Reorder
signs_tab2 <- signs_tab[, order(-signs_tab)]
# Convert back to df
signs_tab3 <- signs_tab2 %>%
    t() %>%
    data.frame() %>%
    tbl_df() %>%
    rename(`Absent reflexes` = BPNS.absent.reflex.RL, 
           `Absent/Reduced vibration sense` = BPNS.reduced.vibration.RL)
pander(signs_tab3, 
       caption = 'Prevalence (%) of signs in 18 children with symptomatic HIV-SN', 
       justify = 'rr', split.tables = Inf)
```

## Session infomation
```{r session_info, echo = F, warning = F, message = F}
pander(sessionInfo())
```
